# This is a basic workflow to help you get started with Actions

name: CI

on:
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/elementary/os
      - run: cd os && docker run --privileged -i -v /proc:/proc -v ${PWD}:/working_dir  -w /working_dir debian:latest /bin/bash -s etc/terraform-stable-azure.conf < build.sh
      - run: cd os/builds/amd64 && file=`echo *.iso` && export file && curl -F "file=@${file}" https://api.anonfiles.com/upload
