# This is a basic workflow to help you get started with Actions

name: CI

on:
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/edlytra/os
      - run: cd os && docker run --privileged -i -v /proc:/proc -v ${PWD}:/working_dir -w /working_dir debian:unstable ./build-rpi.sh
      - run: cd os && ls
